DROP DATABASE kctsdb

/****** Object:  Database [kctsdb]    Script Date: 14.08.2023 12:46:29 ******/
CREATE DATABASE [kctsdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'kctsdb', FILENAME = N'/var/opt/mssql/data/kctsdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'kctsdb_log', FILENAME = N'/var/opt/mssql/data/kctsdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [kctsdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [kctsdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [kctsdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [kctsdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [kctsdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [kctsdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [kctsdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [kctsdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [kctsdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [kctsdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [kctsdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [kctsdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [kctsdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [kctsdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [kctsdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [kctsdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [kctsdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [kctsdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [kctsdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [kctsdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [kctsdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [kctsdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [kctsdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [kctsdb] SET RECOVERY FULL 
GO

ALTER DATABASE [kctsdb] SET  MULTI_USER 
GO

ALTER DATABASE [kctsdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [kctsdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [kctsdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [kctsdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [kctsdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [kctsdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [kctsdb] SET QUERY_STORE = ON
GO

ALTER DATABASE [kctsdb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [kctsdb] SET  READ_WRITE 
GO

USE [kctsdb]
GO

CREATE LOGIN kctsapp
WITH PASSWORD = 'kcts!pass4DB',
DEFAULT_DATABASE = [kctsdb],
CHECK_POLICY = OFF,
CHECK_EXPIRATION = OFF;
GO

USE [kctsdb]
GO

CREATE USER kctsapp FOR LOGIN kctsapp
GO

ALTER ROLE db_owner ADD MEMBER kctsapp
GO